export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_INVOICE = "CREATE_INVOICE";
export const RETRIEVE_INVOICES = "RETRIEVE_INVOICES";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_ALL_INVOICES = "DELETE_ALL_INVOICES";

export const CREATE_CLIENT = "CREATE_CLIENT";
export const RETRIEVE_CLIENTS = "RETRIEVE_CLIENTS";
export const GET_CLIENT = "GET_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_ALL_CLIENTS = "DELETE_ALL_CLIENTS";