export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_TOASTR = "SET_TOASTR";
export const CLEAR_TOASTR = "CLEAR_TOASTR";

export const CREATE_INVOICE = "CREATE_INVOICE";
export const RETRIEVE_INVOICES = "RETRIEVE_INVOICES";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_ALL_INVOICES = "DELETE_ALL_INVOICES";

export const CREATE_CLIENT = "CREATE_CLIENT";
export const RETRIEVE_CLIENTS = "RETRIEVE_CLIENTS";
export const GET_CLIENT = "GET_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_ALL_CLIENTS = "DELETE_ALL_CLIENTS";

export const CREATE_COMPANY = "CREATE_COMPANY";
export const RETRIEVE_COMPANIES = "RETRIEVE_COMPANIES";
export const GET_COMPANY = "GET_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const DELETE_ALL_COMPANIES = "DELETE_ALL_COMPANIES";